### ISSUE TITLE
xcversion not found

### ISSUE THREAD

**Issue by dataviruset** [sinoru/actions-setup-xcode#91]
Used this on a `mac1.metal` EC2 instance.

```
      - name: Set up Xcode
        uses: sinoru/actions-setup-xcode@v2
        with:
          xcode-version: 13.2.1
          apple-id: ${{ inputs.apple_id_email }}
          apple-id-password: ${{ secrets.apple_id_password }}
```

Got this error message:
```
Error: Unable to locate executable file: xcversion. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Seems `xcode-install` (fastlane) is needed. Adding this code snippet before calling `sinoru/actions-setup-xcode` seems to solve the problem.
```
      - name: Install xcode-install
        run: |
          sudo gem install xcode-install
```

Maybe this should be mentioned as a dependency in the README?
Thanks for your contributions!
